/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { TownApiService } from './services/town-api.service';
export { EmployeeApiService } from './services/employee-api.service';
