/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EmployeeHobby } from '../models/employee-hobby';
export interface Employee {
  addressDetail: string;
  cellphone: string;
  createdAt: string;
  email: string;
  employeeHobbies: Array<EmployeeHobby>;
  firstName: string;
  id: number;
  lastName: string;
  nationalId: string;
  town: {
'id': number;
'name': string;
'postCode': string;
'city': {
'id': number;
'name': string;
};
};
  updatedAt: string;
}
