/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UpdateEmployeeHobby } from '../models/update-employee-hobby';
export interface EmployeeUpdateInput {
  addressDetail: string;
  cellphone: string;
  email: string;
  firstName: string;
  lastName: string;
  nationalId: string;
  townId: number;
  updateEmployeeHobbies: Array<UpdateEmployeeHobby>;
}
