/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { City } from '../models/city';
export interface Town {
  city: City;
  id: number;
  name: string;
  postCode: string;
}
