@NOW = 2025-06-24T04:51:21Z
@LATER = 2025-06-24T04:52:21Z
@baseUrl = http://localhost:3000/v1
@pattern = employees

### Get
GET {{baseUrl}}/{{pattern}}

### Create
POST {{baseUrl}}/{{pattern}}

{
    "firstName": "strin3g",
    "lastName": "striwefng",
    "addressDetail": "stwefring",
    "nationalId": "D123456789",
    "email": "abceed@gmail.com",
    "cellphone": "0934345678",
    "townId": 1,
    "employeeHobbies": [
        {
            "id": 0,
            "name": "newwHobby"
        },
        {
            "id": 2
        }
    ]
}

### Update
PUT {{baseUrl}}/{{pattern}}/1

{
    "firstName": "string",
    "lastName": "string",
    "addressDetail": "string",
    "nationalId": "A123456789",
    "email": "abseed@gmail.com",
    "cellphone": "0912345678",
    "townId": 2,
    "employeeHobbies": [
        {
            "id": 1
        },
        {
            "id": 2
        }
    ]
}

### Delete
DELETE {{baseUrl}}/{{pattern}}/1