openapi: 3.0.3
info:
  title: City API
  description: City API
  version: 1.0.0
servers:
  - url: 'http://localhost:3000/v1'
    description: Development server
  - url: 'http://localhost:8080/v1'
    description: Mock server
paths:
  # HobbyAPI
  /hobbies:
    get:
      tags:
        - HobbyAPI
      operationId: getHobbies
      parameters:
        - $ref: '#/components/parameters/pageParam'
        - $ref: '#/components/parameters/pageSizeParam'
        - $ref: '#/components/parameters/orderByParam'
      responses:
        200:
          description: A list of hobbies
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/PaginatedCollection'
                  - type: object
                    required:
                      - items
                    properties:
                      items:
                        type: array
                        items:
                          $ref: '#/components/schemas/Hobby'
    post:
      tags:
        - HobbyAPI
      operationId: createHobby
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HobbyCreateInput'
      responses:
        201:
          description: The created hobby
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hobby'
  /hobbies/{hobbyId}:
    get:
      tags:
        - HobbyAPI
      operationId: getHobby
      parameters:
        - name: hobbyId
          in: path
          required: true
          schema:
            type: integer
          description: The id of the hobby
      responses:
        200:
          description: A hobby
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hobby'
    put:
      tags:
        - HobbyAPI
      operationId: updateHobby
      parameters:
        - name: hobbyId
          in: path
          required: true
          schema:
            type: integer
          description: The id of the hobby
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HobbyUpdateInput'
      responses:
        200:
          description: The updated hobby
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hobby'
    delete:
      tags:
        - HobbyAPI
      operationId: deleteHobby
      parameters:
        - name: hobbyId
          in: path
          required: true
          schema:
            type: integer
          description: The id of the hobby
      responses:
        204:
          description: No Content
  # TownAPI
  /cities:
    get:
      tags:
        - TownAPI
      operationId: getCities
      responses:
        200:
          description: A list of cities
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/City'
  /cities/{cityId}/towns:
    get:
      tags:
        - TownAPI
      operationId: getTowns
      parameters:
        - name: cityId
          in: path
          required: true
          schema:
            type: integer
          description: The id of the city
      responses:
        200:
          description: A city
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Town'
  # EmployeeAPI
  /employees:
    get:
      tags:
        - EmployeeAPI
      operationId: getEmployees
      parameters:
        - $ref: '#/components/parameters/pageParam'
        - $ref: '#/components/parameters/pageSizeParam'
        - $ref: '#/components/parameters/orderByParam'
      responses:
        200:
          description: A list of employees
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/PaginatedCollection'
                  - type: object
                    required:
                      - items
                    properties:
                      items:
                        type: array
                        items:
                          $ref: '#/components/schemas/Employee'
    post:
      tags:
        - EmployeeAPI
      operationId: createEmployee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeCreateInput'
      responses:
        201:
          description: The created employee
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
  /employees/{employeeId}:
    get:
      tags:
        - EmployeeAPI
      operationId: getEmployee
      parameters:
        - name: employeeId
          in: path
          required: true
          schema:
            type: integer
          description: The id of the employee
      responses:
        200:
          description: A employee
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
    put:
      tags:
        - EmployeeAPI
      operationId: updateEmployee
      parameters:
        - name: employeeId
          in: path
          required: true
          schema:
            type: integer
          description: The id of the employee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeUpdateInput'
      responses:
        200:
          description: The updated employee
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
    delete:
      tags:
        - EmployeeAPI
      operationId: deleteEmployee
      parameters:
        - name: employeeId
          in: path
          required: true
          schema:
            type: integer
          description: The id of the employee
      responses:
        204:
          description: No Content

components:
  schemas:
    # HobbyAPI
    Hobby:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string
    HobbyCreateInput:
      type: object
      required:
        - name
      properties:
        name:
          type: string
    HobbyUpdateInput:
      type: object
      required:
        - name
      properties:
        name:
          type: string
    # TownAPI
    City:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string
    Town:
      type: object
      required:
        - id
        - name
        - city
        - postCode
      properties:
        id:
          type: integer
        name:
          type: string
        city:
          $ref: '#/components/schemas/City'
        postCode:
          type: string
    # EmployeeAPI
    Employee:
      type: object
      required:
        - id
        - firstName
        - lastName
        - nationalId
        - email
        - cellphone
        - town
        - addressDetail
        - employeeHobbies
        - createdAt
        - updatedAt
      properties:
        id:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        nationalId:
          type: string
        email:
          type: string
        cellphone:
          type: string
        town:
          type: object
          required:
            - id
            - name
            - postCode
            - city
          properties:
            id:
              type: integer
            name:
              type: string
            postCode:
              type: string
            city:
              type: object
              required:
                - id
                - name
              properties:
                id:
                  type: integer
                name:
                  type: string
        addressDetail:
          type: string
        employeeHobbies:
          type: array
          items:
            $ref: '#/components/schemas/EmployeeHobby'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    EmployeeCreateInput:
      type: object
      required:
        - firstName
        - lastName
        - nationalId
        - email
        - cellphone
        - townId
        - addressDetail
        - updateEmployeeHobbies
      properties:
        firstName:
          type: string
        lastName:
          type: string
        nationalId:
          type: string
        email:
          type: string
        cellphone:
          type: string
        townId:
          type: integer
        addressDetail:
          type: string
        updateEmployeeHobbies:
          type: array
          items:
            $ref: '#/components/schemas/UpdateEmployeeHobby'
    EmployeeUpdateInput:
      type: object
      required:
        - firstName
        - lastName
        - nationalId
        - email
        - cellphone
        - townId
        - addressDetail
        - updateEmployeeHobbies
      properties:
        firstName:
          type: string
        lastName:
          type: string
        nationalId:
          type: string
        email:
          type: string
        cellphone:
          type: string
        townId:
          type: integer
        addressDetail:
          type: string
        updateEmployeeHobbies:
          type: array
          items:
            $ref: '#/components/schemas/UpdateEmployeeHobby'
    EmployeeHobby:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string
    UpdateEmployeeHobby:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string
    # Util
    PaginatedCollection:
      description: a generic type for paginated results
      required:
        - total
        - page
        - pageSize
      properties:
        total:
          type: integer
        page:
          type: integer
        pageSize:
          type: integer
        # Note: `items` must be defined in the operation, otherwise the generated typescript code will not work properly

  parameters:
    pageParam:
      name: page
      in: query
      required: false
      schema:
        type: integer
        minimum: 1
        default: 1
      description: The page number
    pageSizeParam:
      name: pageSize
      in: query
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 10
      description: The page size
    orderByParam:
      name: orderBy
      in: query
      required: false
      schema:
        type: string
      description: The field to order by
