/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createHobby } from '../fn/hobby-api/create-hobby';
import { CreateHobby$Params } from '../fn/hobby-api/create-hobby';
import { deleteHobby } from '../fn/hobby-api/delete-hobby';
import { DeleteHobby$Params } from '../fn/hobby-api/delete-hobby';
import { getHobbies } from '../fn/hobby-api/get-hobbies';
import { GetHobbies$Params } from '../fn/hobby-api/get-hobbies';
import { getHobby } from '../fn/hobby-api/get-hobby';
import { GetHobby$Params } from '../fn/hobby-api/get-hobby';
import { Hobby } from '../models/hobby';
import { PaginatedCollection } from '../models/paginated-collection';
import { updateHobby } from '../fn/hobby-api/update-hobby';
import { UpdateHobby$Params } from '../fn/hobby-api/update-hobby';

@Injectable({ providedIn: 'root' })
export class HobbyApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getHobbies()` */
  static readonly GetHobbiesPath = '/hobbies';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getHobbies()` instead.
   *
   * This method doesn't expect any request body.
   */
  getHobbies$Response(params?: GetHobbies$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedCollection & {
'items': Array<Hobby>;
}>> {
    return getHobbies(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getHobbies$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getHobbies(params?: GetHobbies$Params, context?: HttpContext): Observable<PaginatedCollection & {
'items': Array<Hobby>;
}> {
    return this.getHobbies$Response(params, context).pipe(
      map((r: StrictHttpResponse<PaginatedCollection & {
'items': Array<Hobby>;
}>): PaginatedCollection & {
'items': Array<Hobby>;
} => r.body)
    );
  }

  /** Path part for operation `createHobby()` */
  static readonly CreateHobbyPath = '/hobbies';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createHobby()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createHobby$Response(params: CreateHobby$Params, context?: HttpContext): Observable<StrictHttpResponse<Hobby>> {
    return createHobby(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createHobby$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createHobby(params: CreateHobby$Params, context?: HttpContext): Observable<Hobby> {
    return this.createHobby$Response(params, context).pipe(
      map((r: StrictHttpResponse<Hobby>): Hobby => r.body)
    );
  }

  /** Path part for operation `getHobby()` */
  static readonly GetHobbyPath = '/hobbies/{hobbyId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getHobby()` instead.
   *
   * This method doesn't expect any request body.
   */
  getHobby$Response(params: GetHobby$Params, context?: HttpContext): Observable<StrictHttpResponse<Hobby>> {
    return getHobby(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getHobby$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getHobby(params: GetHobby$Params, context?: HttpContext): Observable<Hobby> {
    return this.getHobby$Response(params, context).pipe(
      map((r: StrictHttpResponse<Hobby>): Hobby => r.body)
    );
  }

  /** Path part for operation `updateHobby()` */
  static readonly UpdateHobbyPath = '/hobbies/{hobbyId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateHobby()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateHobby$Response(params: UpdateHobby$Params, context?: HttpContext): Observable<StrictHttpResponse<Hobby>> {
    return updateHobby(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateHobby$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateHobby(params: UpdateHobby$Params, context?: HttpContext): Observable<Hobby> {
    return this.updateHobby$Response(params, context).pipe(
      map((r: StrictHttpResponse<Hobby>): Hobby => r.body)
    );
  }

  /** Path part for operation `deleteHobby()` */
  static readonly DeleteHobbyPath = '/hobbies/{hobbyId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteHobby()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteHobby$Response(params: DeleteHobby$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteHobby(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteHobby$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteHobby(params: DeleteHobby$Params, context?: HttpContext): Observable<void> {
    return this.deleteHobby$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
