/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Hobby } from '../../models/hobby';
import { HobbyCreateInput } from '../../models/hobby-create-input';

export interface CreateHobby$Params {
      body: HobbyCreateInput
}

export function createHobby(http: HttpClient, rootUrl: string, params: CreateHobby$Params, context?: HttpContext): Observable<StrictHttpResponse<Hobby>> {
  const rb = new RequestBuilder(rootUrl, createHobby.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Hobby>;
    })
  );
}

createHobby.PATH = '/hobbies';
