/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Hobby } from '../../models/hobby';

export interface GetHobby$Params {

/**
 * The id of the hobby
 */
  hobbyId: number;
}

export function getHobby(http: HttpClient, rootUrl: string, params: GetHobby$Params, context?: HttpContext): Observable<StrictHttpResponse<Hobby>> {
  const rb = new RequestBuilder(rootUrl, getHobby.PATH, 'get');
  if (params) {
    rb.path('hobbyId', params.hobbyId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Hobby>;
    })
  );
}

getHobby.PATH = '/hobbies/{hobbyId}';
