/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Hobby } from '../../models/hobby';
import { HobbyUpdateInput } from '../../models/hobby-update-input';

export interface UpdateHobby$Params {

/**
 * The id of the hobby
 */
  hobbyId: number;
      body: HobbyUpdateInput
}

export function updateHobby(http: HttpClient, rootUrl: string, params: UpdateHobby$Params, context?: HttpContext): Observable<StrictHttpResponse<Hobby>> {
  const rb = new RequestBuilder(rootUrl, updateHobby.PATH, 'put');
  if (params) {
    rb.path('hobbyId', params.hobbyId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Hobby>;
    })
  );
}

updateHobby.PATH = '/hobbies/{hobbyId}';
