/* tslint:disable */
 
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { City } from './models/city';
export type { Employee } from './models/employee';
export type { EmployeeCreateInput } from './models/employee-create-input';
export type { EmployeeUpdateInput } from './models/employee-update-input';
export type { PaginatedCollection } from './models/paginated-collection';
export type { Town } from './models/town';
