/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Town } from '../../models/town';

export interface GetTowns$Params {
  /**
   * The id of the city
   */
  cityId: number;
}

export function getTowns(
  http: HttpClient,
  rootUrl: string,
  params: GetTowns$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<Array<Town>>> {
  const rb = new RequestBuilder(rootUrl, getTowns.PATH, 'get');
  if (params) {
    rb.path('cityId', params.cityId, {});
  }

  return http
    .request(
      rb.build({ responseType: 'json', accept: 'application/json', context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<Array<Town>>;
      }),
    );
}

getTowns.PATH = '/cities/{cityId}/towns';
