/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createEmployee } from '../fn/employee-api/create-employee';
import { CreateEmployee$Params } from '../fn/employee-api/create-employee';
import { deleteEmployee } from '../fn/employee-api/delete-employee';
import { DeleteEmployee$Params } from '../fn/employee-api/delete-employee';
import { Employee } from '../models/employee';
import { getEmployee } from '../fn/employee-api/get-employee';
import { GetEmployee$Params } from '../fn/employee-api/get-employee';
import { getEmployees } from '../fn/employee-api/get-employees';
import { GetEmployees$Params } from '../fn/employee-api/get-employees';
import { PaginatedCollection } from '../models/paginated-collection';
import { updateEmployee } from '../fn/employee-api/update-employee';
import { UpdateEmployee$Params } from '../fn/employee-api/update-employee';

@Injectable({ providedIn: 'root' })
export class EmployeeApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getEmployees()` */
  static readonly GetEmployeesPath = '/employees';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getEmployees()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEmployees$Response(
    params?: GetEmployees$Params,
    context?: HttpContext,
  ): Observable<
    StrictHttpResponse<
      PaginatedCollection & {
        items: Array<Employee>;
      }
    >
  > {
    return getEmployees(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getEmployees$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEmployees(
    params?: GetEmployees$Params,
    context?: HttpContext,
  ): Observable<
    PaginatedCollection & {
      items: Array<Employee>;
    }
  > {
    return this.getEmployees$Response(params, context).pipe(
      map(
        (
          r: StrictHttpResponse<
            PaginatedCollection & {
              items: Array<Employee>;
            }
          >,
        ): PaginatedCollection & {
          items: Array<Employee>;
        } => r.body,
      ),
    );
  }

  /** Path part for operation `createEmployee()` */
  static readonly CreateEmployeePath = '/employees';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createEmployee()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createEmployee$Response(
    params: CreateEmployee$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<Employee>> {
    return createEmployee(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createEmployee$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createEmployee(
    params: CreateEmployee$Params,
    context?: HttpContext,
  ): Observable<Employee> {
    return this.createEmployee$Response(params, context).pipe(
      map((r: StrictHttpResponse<Employee>): Employee => r.body),
    );
  }

  /** Path part for operation `getEmployee()` */
  static readonly GetEmployeePath = '/employees/{employeeId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getEmployee()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEmployee$Response(
    params: GetEmployee$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<Employee>> {
    return getEmployee(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getEmployee$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEmployee(
    params: GetEmployee$Params,
    context?: HttpContext,
  ): Observable<Employee> {
    return this.getEmployee$Response(params, context).pipe(
      map((r: StrictHttpResponse<Employee>): Employee => r.body),
    );
  }

  /** Path part for operation `updateEmployee()` */
  static readonly UpdateEmployeePath = '/employees/{employeeId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateEmployee()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateEmployee$Response(
    params: UpdateEmployee$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<Employee>> {
    return updateEmployee(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateEmployee$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateEmployee(
    params: UpdateEmployee$Params,
    context?: HttpContext,
  ): Observable<Employee> {
    return this.updateEmployee$Response(params, context).pipe(
      map((r: StrictHttpResponse<Employee>): Employee => r.body),
    );
  }

  /** Path part for operation `deleteEmployee()` */
  static readonly DeleteEmployeePath = '/employees/{employeeId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteEmployee()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteEmployee$Response(
    params: DeleteEmployee$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<void>> {
    return deleteEmployee(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteEmployee$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteEmployee(
    params: DeleteEmployee$Params,
    context?: HttpContext,
  ): Observable<void> {
    return this.deleteEmployee$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body),
    );
  }
}
