/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { City } from '../models/city';
import { getCities } from '../fn/town-api/get-cities';
import { GetCities$Params } from '../fn/town-api/get-cities';
import { getTowns } from '../fn/town-api/get-towns';
import { GetTowns$Params } from '../fn/town-api/get-towns';
import { Town } from '../models/town';

@Injectable({ providedIn: 'root' })
export class TownApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getCities()` */
  static readonly GetCitiesPath = '/cities';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCities()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCities$Response(
    params?: GetCities$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<Array<City>>> {
    return getCities(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCities$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCities(
    params?: GetCities$Params,
    context?: HttpContext,
  ): Observable<Array<City>> {
    return this.getCities$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<City>>): Array<City> => r.body),
    );
  }

  /** Path part for operation `getTowns()` */
  static readonly GetTownsPath = '/cities/{cityId}/towns';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTowns()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTowns$Response(
    params: GetTowns$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<Array<Town>>> {
    return getTowns(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTowns$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTowns(
    params: GetTowns$Params,
    context?: HttpContext,
  ): Observable<Array<Town>> {
    return this.getTowns$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Town>>): Array<Town> => r.body),
    );
  }
}
