/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Employee } from '../../models/employee';
import { PaginatedCollection } from '../../models/paginated-collection';

export interface GetEmployees$Params {

/**
 * The page number
 */
  page?: number;

/**
 * The page size
 */
  pageSize?: number;

/**
 * The field to order by
 */
  orderBy?: string;
}

export function getEmployees(http: HttpClient, rootUrl: string, params?: GetEmployees$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedCollection & {
'items': Array<Employee>;
}>> {
  const rb = new RequestBuilder(rootUrl, getEmployees.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('orderBy', params.orderBy, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedCollection & {
      'items': Array<Employee>;
      }>;
    })
  );
}

getEmployees.PATH = '/employees';
