/* tslint:disable */
 
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Employee {
  cellphone: string;
  createdAt: string;
  email: string;
  firstName: string;
  id: number;
  lastName: string;
  nationalId: string;
  town: {
    id: number;
    name: string;
    postCode: string;
    city: {
      id: number;
      name: string;
    };
  };
  updatedAt: string;
}
