/* tslint:disable */
 
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EmployeeCreateInput {
  cellphone: string;
  email: string;
  firstName: string;
  lastName: string;
  nationalId: string;
  townId: number;
}
