/* tslint:disable */
 
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * a generic type for paginated results
 */
export interface PaginatedCollection {
  page: number;
  pageSize: number;
  total: number;
}
